name = "fortran-fast-float"
version = "0.1.0"
license = "MIT OR Apache-2.0 OR BSL-1.0"
author = "Federico Perini"
copyright = "Copyright 2026, Federico Perini"
[library]
source-dir = "src"
include-dir = ["include"]
[build]
auto-executables = true
auto-tests = false
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib = "*"
str2real = { git = "https://github.com/Carltoffel/Fortran-String-to-Real" }

[[test]]
name = "check"
source-dir = "test"
main = "check.f90"

